### ISSUE TITLE
Download error occasionally

### ISSUE THREAD

**Issue by Grizzan** [gpailler/MegaApiClient#103]
**Description**:

 Download exist files from the mega

**Actual Behavior**:

Sometimes it catch a unusual error:
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at CG.Web.MegaApiClient.WebClient.GetRequestRaw(Uri url)
   at CG.Web.MegaApiClient.MegaApiClient.Download(INode node, Nullable`1 cancellationToken)
   at DataSyncCenter.Common.MegaSync.DownloadFile(String downloadFilePath, String folderName, String downloadFileNode)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).<---

**Expected Behavior**:

Correctly download

**Steps to Reproduce**:

I don't know how, it looks like a unusual error, I don't know what happen.

**MegaApiClient Version**: 1.6.3

**Comment by Grizzan** [comment]
I've still got this error recently. Error if file is downloaded, then this file cannot be download by MegaApiClient (same error code every times), and I can see it in the Website (Mega.nz) and control it normally. I don't know what's wrong because our code is correctly run for more than 8 month. Maybe there is something changed by mega server like the issue #100 ?

**Comment by gpailler** [comment]
Do you still have this error? Any hint (like a recent upload)?
