### ISSUE TITLE
Multiple Login

### ISSUE THREAD

**Issue by Kurarensu** [gpailler/MegaApiClient#106]
**Description**:

I'm trying to access one mega account in multiple computer simultaneously.

**Actual Behavior**:

CG.Web.MegaApiClient.ApiException was unhandled by user code
  HResult=-2146233088
  Message=API response: ToManyRequestsForThisResource
  Source=MegaApiClient
  StackTrace:
       at CG.Web.MegaApiClient.MegaApiClient.RequestCore[TResponse](RequestBase request, Byte[] key)
       at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Byte[] key)
       at CG.Web.MegaApiClient.MegaApiClient.Login(AuthInfos authInfos)
       at CG.Web.MegaApiClient.MegaApiClient.Login(String email, String password)
       at mCloudStorage.LoginForm.<AttemptLogin>b__1_0() in C:\Users\Ryzen3\Documents\Visual Studio 2015\Projects\mCloudStorage-Client\mCloudStorage-master\mCloudStorage\mCloudStorage\LoginForm.cs:line 70
       at System.Threading.Tasks.Task.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException: 

![megas](https://user-images.githubusercontent.com/11227955/45874996-f6693900-bdc8-11e8-821d-ae368ca395a6.PNG)

**Expected Behavior:**

can login more than 10 user in one mega account

**MegaApiClient Version**:

1.6.3.424

**Comment by gpailler** [comment]
Do you own a paid account or free account? It looks like a limitation on mega.nz side

**Comment by gpailler** [comment]
I guess you should contact Mega directly to enquire about concurrent connection limitation https://mega.nz/contact

**Comment by ayanezr** [comment]
I am having a similar problem. When doing the mega.Login() sometimes it takes too long and never connects, my application stuck and crash. No exception and no errors. Multiple connections are make to Mega. My version is ProLite, any ideas if this is a limitation form MEga side?

**Comment by gpailler** [comment]
Could you try to subscribe to the MegaApiClient.ApiRequestFailed event and check if the event is raised during login? How many connections are you making? Are you creating several parallel connections?
