### ISSUE TITLE
API fails in GetNodesFromLinkAsync

### ISSUE THREAD

**Issue by ManlyMarco** [gpailler/MegaApiClient#136]
**Description**:
GetNodesFromLinkAsync started failing every time recently.

**Actual Behavior**:
There's an internal exception being thrown and the client retries until it runs out of retries and fails.
```
System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'Newtonsoft.Json.Linq.JArray'.
   at CG.Web.MegaApiClient.MegaApiClient.RequestCore[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.GetNodesFromLink(Uri uri)
   at CG.Web.MegaApiClient.MegaApiClient.<>c__DisplayClass81_0.<GetNodesFromLinkAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Expected Behavior**:
Lack of explosions.

**Steps to Reproduce**:

1. Create a new client instance.
2. Log in to an account (not sure if necessary).
3. Run GetNodesFromLinkAsync on a mega folder link.

**MegaApiClient Version**: v1.7.1

**Comment by ManlyMarco** [comment]
It looks like the issue resolved itself. I'm guessing it was an issue on the mega's side.
