### ISSUE TITLE
Significant number of Operation has timed out

### ISSUE THREAD

**Issue by mrjarhead** [gpailler/MegaApiClient#164]
When downloading files with the client, I'm getting the the below exception (rough estimate of 5-10% of downloads).  The issue seems fairly random and unpredictable:  

System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.WebException: The operation has timed out.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at CG.Web.MegaApiClient.BufferedStream.FillBuffer()
   at CG.Web.MegaApiClient.BufferedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at CG.Web.MegaApiClient.MegaAesCtrStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at CG.Web.MegaApiClient.MegaApiClient.SaveStream(Stream stream, String outputFile)
   at CG.Web.MegaApiClient.MegaApiClient.DownloadFile(INode node, String outputFile, Nullable`1 cancellationToken)

Before I pull down the code and work through it, any thoughts or words of wisdom?  Also, is there a way to re-start a failed download, i.e. have it re-start at the byte location where it failed? 

Appreciate any help in this.

Thanks!

**Comment by gpailler** [comment]
I was experiencing this kind of timeout exception from time to time when running the unit tests. My assumption is that Mega is applying some kind of throttling. Are you using a free or paid account?

From a technical point of view, it should be possible to restart the download of the failed chunks but it's not implemented in MegaApiClient.  I'm open to PR though 😉

**Comment by mrjarhead** [comment]
Ha will do!  I'm getting this on a paid account running against public folders, and that was my assumption also i.e. some type of throttling.  What has me scratching my head is that I see it regardless if I'm running on 1 thread or 20.  I'll crack open the code and see if I can add some (optional) error/retry logic - if all goes well, I'll PR it back in.  

Thanks for the help!
