### ISSUE TITLE
An error occurs in the "GetNodes()" function approximately three hours after logging in.

### ISSUE THREAD

**Issue by AngleGN** [gpailler/MegaApiClient#172]
First of all, thank you for making a good library 👍

**Description**:

*what are you trying to do*
I am periodically bringing up nodes and extracting shared links.

**Actual Behavior**:
Approximately 3 hours after execution, the following error occurs when calling the "GetNodes()" function :(

*what happens*
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at CG.Web.MegaApiClient.Crypto.DecryptKey(Byte[] data, Byte[] key)
   at CG.Web.MegaApiClient.Node.OnDeserialized(StreamingContext ctx)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Newtonsoft.Json.Serialization.JsonContract.<>c__DisplayClass57_0.<CreateSerializationCallback>b__0(Object o, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonContract.InvokeOnDeserialized(Object o, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at CG.Web.MegaApiClient.Serialization.NodeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at CG.Web.MegaApiClient.Serialization.GetNodesResponse.OnDeserialized(StreamingContext ctx)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Newtonsoft.Json.Serialization.JsonContract.<>c__DisplayClass57_0.<CreateSerializationCallback>b__0(Object o, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonContract.InvokeOnDeserialized(Object o, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at CG.Web.MegaApiClient.Serialization.GetNodesResponseConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at CG.Web.MegaApiClient.MegaApiClient.RequestCore[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.GetNodes()
```

**MegaApiClient Version**:
1.9.0

It happens after a few hours.
Log in to MEGA with your browser and it will be resolved.
My guess is that the session will expire.

How can we solve this?

**Comment by gpailler** [comment]
Hi,

I'm expecting to have an exception raised by the `RequestCore` method if the session expires. Are you able to dump the json content returned by Mega in Visual Studio when you experience the exception?

It would be great if you can create a small repo program so I can reproduce and investigate on my side.
Thanks

**Comment by GODNIN** [comment]
I think I can give you the "ResponseJson" of the "ApiRequestFailed" event, right?
So I'm watching the "ApiRequestFailed" event.

Thank you for your prompt reply.

**Comment by gpailler** [comment]
If think that in your case, ApiRequestFailed is not raised. The call to the Mega API returns Ok but the Json is corrupted somehow.
If you have a debugger attached, you can probably dump the json by navigating in the callstack

**Comment by GODNIN** [comment]
Checked it.

The same error just occurred and the value of "JsonData" for the "RequestCore" function was obtained.

```
jsonData = {[
  {
    "ok0": [
      {
        "h": "VE8jCSZY",
        "ha": "2Q29o0BU93eQTBOBjWAq_Q",
        "k": "1C9Wby3qrA3i_LRChkHy6A"
      },
      {
        "h": "MJsUAKRQ",
        "ha": "C0kMHvJEv_U9AAcfxDxXuQ",
        "k": "tvWCmI9FSOLOImY70bq...
```

This is the value of "data".

```
data = "{\r\n  \"ok0\": [\r\n    {\r\n      \"h\": \"VE8jCSZY\",\r\n      \"ha\": \"2Q29o0BU93eQTBOBjWAq_Q\",\r\n      \"k\": \"1C9Wby3qrA3i_LRChkHy6A\"\r\n    },\r\n    {\r\n      \"h\": \"MJsUAKRQ\",\r\n      \"ha\": \"C0kMHvJEv_U9AAcfxDxXuQ\",\r\n      \"k\": \...
```

I think the data is wrong.

**Comment by gpailler** [comment]
Could you paste the whole data? It's encrypted and cannot be decrypted without your master key but I can check if the Data is valid

**Comment by GODNIN** [comment]
I masked the email because it's a business account.

Please understand.

[data.txt](https://github.com/gpailler/MegaApiClient/files/6709318/data.txt)

**Comment by gpailler** [comment]
Thanks for the file. I applied some formatting on it to have a valid json object. I will try to find some time to investigate the issue.
[data.txt](https://github.com/gpailler/MegaApiClient/files/6710160/data.txt)

**Comment by gpailler** [comment]
1.10.0 released
