### ISSUE TITLE
ResourceNotExists Error

### ISSUE THREAD

**Issue by B1QB0SS** [gpailler/MegaApiClient#35]
whenever i try to to get Nodes after logging in i get this error 

CG.Web.MegaApiClient.ApiException: API response: ResourceNotExists

**Comment by silvermcd123** [comment]
confirm

**Comment by B1QB0SS** [comment]
CG.Web.MegaApiClient.ApiException: API response: ResourceNotExists
   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Object context)
   at CG.Web.MegaApiClient.MegaApiClient.Login(AuthInfos authInfos)
   at CG.Web.MegaApiClient.MegaApiClient.Login(String email, String password)
   at Mega.Login() in mypath\Mega.cs:line 20

**Comment by B1QB0SS** [comment]
CG.Web.MegaApiClient.ApiException: API response: ResourceNotExists
   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Object context)
   at CG.Web.MegaApiClient.MegaApiClient.Login(AuthInfos authInfos)
   at CG.Web.MegaApiClient.MegaApiClient.Login(String email, String password)
   at Mega.Login() in mypath\Mega.cs:line 20

**Comment by gpailler** [comment]
Hello @B1QB0SS. ResourceNotExists exception is raised when username/password is invalid. Are you sure about your credentials? Do you use some special characters on it?
